apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: auto-system-reserved-worker
spec:
  autoSizingReserved: true
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: ""
