apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  tokenConfig:
    accessTokenMaxAgeSeconds: 2419200 # 28d
  identityProviders:
    - name: RedHat_Internal_SSO
      mappingMethod: claim
      type: OpenID
      openID:
        clientID: bb6f2fabde1eea8011d8
        clientSecret:
          name: dex-rh-sso
        extraScopes:
        - email
        - profile
        claims:
          preferredUsername:
          - preferred_username
          - email
          name:
          - name
          email:
          - email
        issuer: https://idp.ci.openshift.org
