apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker-build
  name: 98-mount-instance-storage
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - path: /usr/local/bin/find_and_mount_first_matching_nvme.sh
        mode: 0755
        overwrite: true
        contents:
          source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKCiMgSW5pdGlhbGl6ZSBhIHZhcmlhYmxlIHRvIHN0b3JlIHRoZSBmaXJzdCBtYXRjaGluZyBkZXZpY2UKZmlyc3RfbWF0Y2hpbmdfZGV2aWNlPSIiCgojIEZpbmQgYWxsIE5WTWUgZGV2aWNlcwpmb3IgZGV2aWNlIGluIC9kZXYvbnZtZSpuMTsgZG8KICAgICMgQ2hlY2sgaWYgdGhlIGRldmljZSBoYXMgdGhlIGRlc2lyZWQgbW9kZWwKICAgIG1vZGVsPSQodWRldmFkbSBpbmZvIC0tcXVlcnk9YWxsIC0tbmFtZT0iJGRldmljZSIgfCBncmVwICJJRF9NT0RFTD0iKQogICAgaWYgW1sgJG1vZGVsID09ICoiQW1hem9uIEVDMiBOVk1lIEluc3RhbmNlIFN0b3JhZ2UiKiBdXTsgdGhlbgogICAgICAgIGZpcnN0X21hdGNoaW5nX2RldmljZT0iJGRldmljZSIKICAgICAgICBicmVhawogICAgZmkKZG9uZQoKIyBFeGl0IGlmIG5vIG1hdGNoaW5nIGRldmljZSB3YXMgZm91bmQKaWYgW1sgLXogIiRmaXJzdF9tYXRjaGluZ19kZXZpY2UiIF1dOyB0aGVuCiAgICBlY2hvICJObyBtYXRjaGluZyBkZXZpY2Ugd2FzIGZvdW5kIgogICAgZXhpdCAxCmZpCgojIENoZWNrIGlmIHRoZSBkZXZpY2Ugc2l6ZSBpcyBncmVhdGVyIHRoYW4gMTAwIEdCCnNpemU9JChsc2JsayAtYiAtZCAtbyBTSVpFIC1uICIkZmlyc3RfbWF0Y2hpbmdfZGV2aWNlIikKaWYgKCggc2l6ZSA8PSAxMDAgKiAxMDI0ICogMTAyNCAqIDEwMjQgKSk7IHRoZW4KICAgIGVjaG8gIiRmaXJzdF9tYXRjaGluZ19kZXZpY2UgaXMgc21hbGxlciB0aGFuIDEwMCBHQiwgc2tpcHBpbmciCiAgICBleGl0IDEKZmkKCiMgQ2hlY2sgaWYgdGhlIGRldmljZSBpcyB1bmZvcm1hdHRlZCBvciBoYXMgYW4gWEZTIGZpbGVzeXN0ZW0KZnNfdHlwZT0kKGxzYmxrIC1mIC1kIC1vIEZTVFlQRSAtbiAiJGZpcnN0X21hdGNoaW5nX2RldmljZSIpCmlmIFtbIC1uICIkZnNfdHlwZSIgJiYgIiRmc190eXBlIiAhPSAieGZzIiBdXTsgdGhlbgogICAgZWNobyAiJGZpcnN0X21hdGNoaW5nX2RldmljZSBoYXMgYSBkaWZmZXJlbnQgZmlsZXN5c3RlbSAoJGZzX3R5cGUpLCBza2lwcGluZyIKICAgIGV4aXQgMQpmaQoKaWYgW1sgLXogIiRmc190eXBlIiBdXTsgdGhlbgogICAgZWNobyAiRm9ybWF0dGluZyAkZmlyc3RfbWF0Y2hpbmdfZGV2aWNlIHRvIFhGUyIKICAgIG1rZnMueGZzIC1mICIkZmlyc3RfbWF0Y2hpbmdfZGV2aWNlIgplbHNlCiAgICBlY2hvICIkZmlyc3RfbWF0Y2hpbmdfZGV2aWNlIGFscmVhZHkgaGFzIGFuIFhGUyBmaWxlc3lzdGVtIgpmaQoKZWNobyAiTW91bnRpbmcgJGZpcnN0X21hdGNoaW5nX2RldmljZSB0byAvdmFyL2xpYi9jb250YWluZXJzIgpta2RpciAtcCAvdmFyL2xpYi9jb250YWluZXJzCm1vdW50ICIkZmlyc3RfbWF0Y2hpbmdfZGV2aWNlIiAvdmFyL2xpYi9jb250YWluZXJzCmVjaG8gIk1vdW50ZWQgJGZpcnN0X21hdGNoaW5nX2RldmljZSB0byAvdmFyL2xpYi9jb250YWluZXJzIgo=
    systemd:
      units:
      - name: mount-instance-storage.service
        enabled: true
        contents: |
          [Unit]
          Description=Find and Mount Instance Storage
          After=var.mount
          Before=local-fs.target crio.service
          Wants=local-fs.target

          [Service]
          Type=oneshot
          ExecStart=/usr/local/bin/find_and_mount_first_matching_nvme.sh
          ExecStartPost=/sbin/restorecon -R /var/lib/containers/
          RemainAfterExit=yes

          [Install]
          WantedBy=multi-user.target graphical.target
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    custom-kubelet: enabled
    machineconfiguration.openshift.io/mco-built-in: ""
    pools.operator.machineconfiguration.openshift.io/worker: ""
  name: worker-build
spec:
  machineConfigSelector:
    matchExpressions:
      - { key: machineconfiguration.openshift.io/role, operator: In, values: [worker-build, worker] }
    # matchLabels:
    #   machineconfiguration.openshift.io/role: worker-build
  maxUnavailable: 20
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-build: ""
  paused: false
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "32768"
    machine.openshift.io/vCPU: "16"
    ci-scheduling.ci.openshift.io/keep-node: "true"
  labels:
    ci-machineset-class: builds
    machine.openshift.io/cluster-api-cluster: build01-9hdwj
    ci-scheduling.ci.openshift.io/keep-node: "true"
  name: build01-9hdwj-ci-builds-worker-us-east-1a-test
  namespace: openshift-machine-api
spec:
  deletePolicy: Oldest
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: build01-9hdwj
      machine.openshift.io/cluster-api-machineset: build01-9hdwj-ci-builds-worker-us-east-1a-test
  template:
    metadata:
      labels:
        ci-scheduling.ci.openshift.io/keep-node: "true"
        machine.openshift.io/cluster-api-cluster: build01-9hdwj
        machine.openshift.io/cluster-api-machine-role: worker-build
        machine.openshift.io/cluster-api-machine-type: worker-build
        machine.openshift.io/cluster-api-machineset: build01-9hdwj-ci-builds-worker-us-east-1a-test
    spec:
      lifecycleHooks: {}
      metadata:
        labels:
          ci-workload: builds
          node-role.kubernetes.io/worker-build: ""
          ci-scheduling.ci.openshift.io/keep-node: "true"
      providerSpec:
        value:
          ami:
            id: ami-06f85a7940faa3217
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 5000
              kmsKey: {}
              throughput: 500
              volumeSize: 200
              volumeType: gp3
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: build01-9hdwj-worker-profile
          instanceType: m5a.4xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-1a
            region: us-east-1
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - build01-9hdwj-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - build01-9hdwj-private-us-east-1a
          tags:
          - name: kubernetes.io/cluster/build01-9hdwj
            value: owned
          - name: ci-cluster
            value: build01
          - name: ci-workload
            value: builds
          userDataSecret:
            name: worker-user-data
      taints:
      - effect: NoSchedule
        key: node-role.kubernetes.io/ci-builds-worker
        value: ci-builds-worker
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pod-demo
  labels:
    app: pod-demo
  namespace: bechen
spec:
  selector:
    matchLabels:
      app: pod-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-demo
    spec:
      tolerations:
      - key: node-role.kubernetes.io/ci-builds-worker
        operator: "Equal"
        value: ci-builds-worker
        effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/worker-build: ""
      containers:
        - name: backserver
          image: busybox
          args: [ httpd, -f, -p, '5000', -h, /var/www ]
          volumeMounts:
            - name: bear-test
              mountPath: /var/www
          ports:
            - containerPort: 8080
      volumes:
        - name: bear-test
          persistentVolumeClaim:
            claimName: bear-test 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bear-test
  namespace: bechen
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi 
  storageClassName: gp3-csi
