apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
    build-only: "true"
  name: 98-mount-instance-storage
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - path: /usr/local/bin/find_and_mount_first_matching_nvme.sh
        mode: 0755
        overwrite: true
        contents:
          source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKCiMgSW5pdGlhbGl6ZSBhIHZhcmlhYmxlIHRvIHN0b3JlIHRoZSBmaXJzdCBtYXRjaGluZyBkZXZpY2UKZmlyc3RfbWF0Y2hpbmdfZGV2aWNlPSIiCgojIEZpbmQgYWxsIE5WTWUgZGV2aWNlcwpmb3IgZGV2aWNlIGluIC9kZXYvbnZtZSpuMTsgZG8KICAgICMgQ2hlY2sgaWYgdGhlIGRldmljZSBoYXMgdGhlIGRlc2lyZWQgbW9kZWwKICAgIG1vZGVsPSQodWRldmFkbSBpbmZvIC0tcXVlcnk9YWxsIC0tbmFtZT0iJGRldmljZSIgfCBncmVwICJJRF9NT0RFTD0iKQogICAgaWYgW1sgJG1vZGVsID09ICoiQW1hem9uIEVDMiBOVk1lIEluc3RhbmNlIFN0b3JhZ2UiKiBdXTsgdGhlbgogICAgICAgIGZpcnN0X21hdGNoaW5nX2RldmljZT0iJGRldmljZSIKICAgICAgICBicmVhawogICAgZmkKZG9uZQoKIyBFeGl0IGlmIG5vIG1hdGNoaW5nIGRldmljZSB3YXMgZm91bmQKaWYgW1sgLXogIiRmaXJzdF9tYXRjaGluZ19kZXZpY2UiIF1dOyB0aGVuCiAgICBlY2hvICJObyBtYXRjaGluZyBkZXZpY2Ugd2FzIGZvdW5kIgogICAgZXhpdCAwCmZpCgojIENoZWNrIGlmIHRoZSBkZXZpY2Ugc2l6ZSBpcyBncmVhdGVyIHRoYW4gMTAwIEdCCnNpemU9JChsc2JsayAtYiAtZCAtbyBTSVpFIC1uICIkZmlyc3RfbWF0Y2hpbmdfZGV2aWNlIikKaWYgKCggc2l6ZSA8PSAxMDAgKiAxMDI0ICogMTAyNCAqIDEwMjQgKSk7IHRoZW4KICAgIGVjaG8gIiRmaXJzdF9tYXRjaGluZ19kZXZpY2UgaXMgc21hbGxlciB0aGFuIDEwMCBHQiwgc2tpcHBpbmciCiAgICBleGl0IDAKZmkKCiMgQ2hlY2sgaWYgdGhlIGRldmljZSBpcyB1bmZvcm1hdHRlZCBvciBoYXMgYW4gWEZTIGZpbGVzeXN0ZW0KZnNfdHlwZT0kKGxzYmxrIC1mIC1kIC1vIEZTVFlQRSAtbiAiJGZpcnN0X21hdGNoaW5nX2RldmljZSIpCmlmIFtbIC1uICIkZnNfdHlwZSIgJiYgIiRmc190eXBlIiAhPSAieGZzIiBdXTsgdGhlbgogICAgZWNobyAiJGZpcnN0X21hdGNoaW5nX2RldmljZSBoYXMgYSBkaWZmZXJlbnQgZmlsZXN5c3RlbSAoJGZzX3R5cGUpLCBza2lwcGluZyIKICAgIGV4aXQgMApmaQoKaWYgW1sgLXogIiRmc190eXBlIiBdXTsgdGhlbgogICAgZWNobyAiRm9ybWF0dGluZyAkZmlyc3RfbWF0Y2hpbmdfZGV2aWNlIHRvIFhGUyIKICAgIGlmIG1rZnMueGZzIC1mICIkZmlyc3RfbWF0Y2hpbmdfZGV2aWNlIjsgdGhlbgogICAgICAgIGVjaG8gIlN1Y2Nlc3NmdWxseSBmb3JtYXR0ZWQgJGZpcnN0X21hdGNoaW5nX2RldmljZSB0byBYRlMiCiAgICBlbHNlCiAgICAgICAgZWNobyAiRmFpbGVkIHRvIGZvcm1hdCAkZmlyc3RfbWF0Y2hpbmdfZGV2aWNlIHRvIFhGUyIKICAgICAgICBleGl0IDEKICAgIGZpCmVsc2UKICAgIGVjaG8gIiRmaXJzdF9tYXRjaGluZ19kZXZpY2UgYWxyZWFkeSBoYXMgYW4gWEZTIGZpbGVzeXN0ZW0iCmZpCgplY2hvICJNb3VudGluZyAkZmlyc3RfbWF0Y2hpbmdfZGV2aWNlIHRvIC92YXIvbGliL2NvbnRhaW5lcnMiCm1rZGlyIC1wIC92YXIvbGliL2NvbnRhaW5lcnMKaWYgbW91bnQgIiRmaXJzdF9tYXRjaGluZ19kZXZpY2UiIC92YXIvbGliL2NvbnRhaW5lcnM7IHRoZW4KICAgIGVjaG8gIk1vdW50ZWQgJGZpcnN0X21hdGNoaW5nX2RldmljZSB0byAvdmFyL2xpYi9jb250YWluZXJzIgogICAgZWNobyAiUmV0b3JpbmcgU0VMaW51eCBjb250ZXh0IgogICAgL3NiaW4vcmVzdG9yZWNvbiAtUiAvdmFyL2xpYi9jb250YWluZXJzLwplbHNlCiAgICBlY2hvICJGYWlsZWQgdG8gbW91bnQgJGZpcnN0X21hdGNoaW5nX2RldmljZSB0byAvdmFyL2xpYi9jb250YWluZXJzIgogICAgZXhpdCAxCmZpCg==
    systemd:
      units:
      - name: mount-instance-storage.service
        enabled: true
        contents: |
          [Unit]
          Description=Find and Mount Instance Storage
          DefaultDependencies=no
          After=var.mount
          Before=local-fs.target crio.service

          [Service]
          Type=oneshot
          ExecStart=/usr/local/bin/find_and_mount_first_matching_nvme.sh
          ExecStartPost=
          RemainAfterExit=yes

          [Install]
          WantedBy=local-fs.target multi-user.target graphical.target
