apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: build11
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  source:
    path: cluster-config/build11/manifests
    repoURL: 'https://github.com/bear-redhat/release'
    targetRevision: issue/DPTP-4115
  sources: []
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
